version: '3'

services:
   db:
     image: mariadb:latest
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

   reverse-proxy01:
     depends_on:
       - wordpress
     restart: always
     image: nginx
     volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
       - ./letsencrypt/:/etc/letsencrypt/
     ports:
       - 443:443
